// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoPay.Data;

namespace VideoPay.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20180629144736_update01")]
    partial class update01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoPay.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("HasPaid");

                    b.Property<string>("ItemName")
                        .HasMaxLength(128);

                    b.Property<string>("LastUpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValue("GETDATE()");

                    b.Property<int>("OrderAmt");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(128);

                    b.Property<string>("PayType")
                        .HasMaxLength(128);

                    b.Property<string>("Remark");

                    b.Property<string>("SN")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("OrderNo")
                        .IsUnique()
                        .HasFilter("[OrderNo] IS NOT NULL");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
